"""Lock-parity check: requirements.lock must pin every dev-extra requirement.

CI installs strictly from the lock (``pip install --require-hashes -r
requirements.lock``), so a package declared in the ``dev`` extra but absent
from the lock is simply *not installed* in any job. Tests guarded by
``pytest.importorskip`` then skip silently and the job still goes green — the
gate reports success while the feature it is supposed to cover is unverified.

That is not hypothetical: ``jsonschema`` entered the ``dev`` extra on
2026-06-18 but the lock had last been regenerated on 2026-06-16, so the Tier-B
JSON-Schema tool-argument validation tests ``importorskip``-skipped in every
required job until the 2026-07-25 audit caught it.

This check fails loud on that drift class: every requirement named in the
``dev`` extra of ``pyproject.toml`` must appear as a pinned distribution in
``requirements.lock``. It also verifies the lock's autogenerated header still
records the expected compile command, so a lock regenerated from a different
input (a missing ``--extra dev``, say) is caught even though the resulting
name set might coincidentally look complete.

Deliberately *not* checked: whether each locked version satisfies the dev
extra's version specifier. That needs a PEP 440 implementation, and this
script is stdlib-only (ADR-004 discipline applies to tooling too) — a
hand-rolled approximation would be worse than none. Name-level parity is the
drift that actually recurred.

Run from the repo root: ``python scripts/check_lock_parity.py``.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
LOCK_PATH = REPO_ROOT / "requirements.lock"

# The extra the lock is compiled from, and the command that regenerates it.
# Both appear in the lock's autogenerated header; keep them in sync with the
# "Install dependencies" step in .github/workflows/ci.yml.
LOCK_EXTRA = "dev"
COMPILE_COMMAND = (
    "uv pip compile pyproject.toml --extra dev --generate-hashes -o requirements.lock"
)

# A requirement string starts with its distribution name; everything from the
# first extras bracket, version specifier, or environment marker is metadata.
_REQUIREMENT_NAME = re.compile(r"^\s*([A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?)")
# uv writes one `name==version \` line per pinned distribution.
_LOCKED_PIN = re.compile(
    r"^([A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?)==", re.MULTILINE
)


def normalize(name: str) -> str:
    """Normalize a distribution name per PEP 503 (``Foo_Bar`` -> ``foo-bar``)."""
    return re.sub(r"[-_.]+", "-", name).lower()


def requirement_name(requirement: str) -> str | None:
    """Extract the distribution name from a PEP 508 requirement string."""
    match = _REQUIREMENT_NAME.match(requirement)
    return normalize(match.group(1)) if match else None


def declared_dev_requirements() -> set[str]:
    """Return the normalized distribution names in pyproject's ``dev`` extra."""
    with PYPROJECT_PATH.open("rb") as handle:
        pyproject = tomllib.load(handle)

    extras = pyproject.get("project", {}).get("optional-dependencies", {})
    if LOCK_EXTRA not in extras:
        raise SystemExit(
            f"pyproject.toml declares no '{LOCK_EXTRA}' extra under "
            "[project.optional-dependencies]; check_lock_parity.py needs it to "
            "know what the lock is supposed to contain."
        )

    names = {requirement_name(entry) for entry in extras[LOCK_EXTRA]}
    return {name for name in names if name is not None}


def locked_distributions(lock_text: str) -> set[str]:
    """Return the normalized distribution names pinned in the lock."""
    return {normalize(name) for name in _LOCKED_PIN.findall(lock_text)}


def check_header(lock_text: str, failures: list[str]) -> None:
    """The lock must record that it was compiled from the expected command."""
    if COMPILE_COMMAND not in lock_text:
        failures.append(
            "requirements.lock's autogenerated header does not record the "
            f"expected compile command ({COMPILE_COMMAND}). The lock may have "
            "been compiled from a different input or extra set."
        )


def check_parity(declared: set[str], locked: set[str], failures: list[str]) -> None:
    """Every declared dev requirement must be pinned in the lock."""
    for name in sorted(declared - locked):
        failures.append(
            f"'{name}' is declared in the '{LOCK_EXTRA}' extra of pyproject.toml "
            "but is not pinned in requirements.lock, so CI's --require-hashes "
            "install will not install it and any test guarding on it will skip."
        )


def main() -> int:
    lock_text = LOCK_PATH.read_text(encoding="utf-8")
    declared = declared_dev_requirements()
    locked = locked_distributions(lock_text)

    failures: list[str] = []
    check_header(lock_text, failures)
    check_parity(declared, locked, failures)

    if failures:
        print("Lock-parity check failed:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        print(
            f"\nRegenerate the lock, then commit it:\n    {COMPILE_COMMAND}",
            file=sys.stderr,
        )
        return 1

    print(
        f"Lock-parity check passed: every '{LOCK_EXTRA}' extra requirement is "
        "pinned in requirements.lock."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
